import tw from "twin.macro";
import { BsCreditCard } from "react-icons/bs";
import { FaPassport, FaIdCard } from "react-icons/fa";
import { AiOutlineIdcard } from "react-icons/ai";

export const Heading = tw.h1`sm:text-3xl text-2xl font-black md:mb-2 text-primary-500`;
export const Description = tw.p`mx-auto leading-relaxed text-base`;
export const Header = tw.header`flex flex-col sm:flex-row justify-between w-full mb-4`;
export const HeaderItem = tw.div`mb-3`;
export const Button = tw.button`inline-flex flex-auto items-center transition duration-300 bg-primary-500 hover:bg-primary-700 hocus:outline-none hocus:text-white text-white font-medium p-3 sm:p-6 no-underline appearance-none`;
export const SearchButton = tw.button`flex mx-auto items-center text-white bg-primary-500 border-0 py-3 px-12 focus:outline-none hover:bg-primary-700 rounded-4xl text-lg`;
export const Container = tw.div`container w-full mx-auto`;
export const Row = tw.div`lg:w-1/2 md:w-2/3 mx-auto`;
export const FormField = tw.div`p-2 w-full mb-4`;
export const Card = tw.div`mt-6 h-full flex items-center border-gray-200 border p-4 shadow-md rounded-lg`;
export const DriverLicenseIcon = tw(AiOutlineIdcard)`text-primary-500  w-14 h-14 mr-10`;
export const CreditCardIcon = tw(BsCreditCard)`text-primary-500  w-14 h-14 mr-10`;
export const IdCardIcon = tw(FaIdCard)`text-primary-500  w-14 h-14 mr-10`;
export const PassportIcon = tw(FaPassport)`text-primary-500  w-14 h-14 mr-10`;
export const CardItem = tw.div`flex-grow`;
export const CardTitle = tw.span`text-gray-900 font-medium`;
export const CardInfo = tw.p`text-gray-500`;
export const CardButton = tw(Button)`font-normal mt-2 p-1 px-2 rounded-2xl`;
export const ToggleButton = tw.span`absolute inset-y-0 right-5 flex items-center  cursor-pointer`;
export const SubmitButton = tw.button`flex mx-auto items-center text-white bg-primary-500 border-0 py-2 px-9 focus:outline-none hover:bg-primary-700 rounded-4xl text-lg`;
export const Input = tw.input`w-full bg-opacity-50 rounded border border-gray-300 focus:border-primary-500 focus:bg-white focus:ring-2 focus:ring-primary-200 text-base outline-none text-gray-700 py-2 px-4 leading-8 transition-colors duration-200 ease-in-out rounded-4xl placeholder-gray-400`;
export const Label = tw.label`leading-7 text-sm text-gray-600`;
export const Form = tw.form`mx-auto`;
export const Select = tw.select`block appearance-none w-full bg-opacity-50 border border-gray-300 text-gray-600 py-3 px-4 pr-8 rounded-4xl leading-tight focus:outline-none focus:bg-white focus:border-primary-500`;
export const SelectToggle = tw.div`pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700`;
